name: Pruebas

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar TBB
        run: sudo apt-get update && sudo apt-get install -y libtbb-dev

      - name: Compilar y ejecutar
        run: make
